name: OddItem
main: info.somethingodd.OddItem.OddItemBase
load: STARTUP
version: ${pom.version}
website: ${pom.url}
author: petteyg359
description: Item database stuff.
commands:
    odditem:
        aliases: oi
        permission: odditem.alias
        usage:  |
                /<command> [alias]
                Shows aliases of held item or <alias>
    odditeminfo:
        aliases: oii
        permission: odditem.info
        usage:  |
                /<command>
                Shows information about loaded items/aliases
    odditemreload:
        aliases: oir
        permission: odditem.reload
        usage:  |
                /<command>
                Reload configuration from disk
permissions:
    odditem:
        children:
            odditem.alias: true
            odditem.info: true
        default: true
    odditem.alias:
        default: true
    odditem.info:
        default: true
    odditem.reload:
        default: op
